[build]
  command = "npm run build"
  publish = "_site"
  functions = "netlify/functions"

[functions]
  included_files = ["protected_documents/**"]

[build.environment]
  NODE_VERSION = "20"
  ADMIN_PASSWORD_HASH = "5523d8cbbaa1a7c1dda2839929ad199e1e90b534c1dc54f4dc73427297766fd2"
  ADMIN_PASSWORD_SALT = "cdfc6609f037b959358fec5f4976c74e"

[[redirects]]
  from = "https://www.seculex.org/*"
  to = "https://seculex.org/:splat"
  status = 301
  force = true

